/**
 * generated by Xtext 2.10.0
 */
package org.xtext.blogPostDSL.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.blogPostDSL.BlogPostDSLPackage;
import org.xtext.blogPostDSL.ItemElement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Item Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ItemElementImpl extends MinimalEObjectImpl.Container implements ItemElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ItemElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BlogPostDSLPackage.Literals.ITEM_ELEMENT;
  }

} //ItemElementImpl
