/**
 * generated by Xtext 2.10.0
 */
package org.xtext.blogPostDSL.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.blogPostDSL.BlogPostDSLPackage;
import org.xtext.blogPostDSL.SubItemElement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sub Item Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SubItemElementImpl extends MinimalEObjectImpl.Container implements SubItemElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SubItemElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BlogPostDSLPackage.Literals.SUB_ITEM_ELEMENT;
  }

} //SubItemElementImpl
