/**
 * generated by Xtext 2.10.0
 */
package org.xtext.blogPostDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Item Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.blogPostDSL.BlogPostDSLPackage#getItemElement()
 * @model
 * @generated
 */
public interface ItemElement extends EObject
{
} // ItemElement
