/**
 * generated by Xtext 2.10.0
 */
package org.xtext.blogPostDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sub Item Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.blogPostDSL.BlogPostDSLPackage#getSubItemElement()
 * @model
 * @generated
 */
public interface SubItemElement extends EObject
{
} // SubItemElement
