/*
 * generated by Xtext 2.10.0
 */
package org.xtext.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.services.BlogPostDSLGrammarAccess;

@SuppressWarnings("all")
public class BlogPostDSLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected BlogPostDSLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Article_Blog_LeftCurlyBracketKeyword_0_or_LeftCurlyBracketKeyword_0;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (BlogPostDSLGrammarAccess) access;
		match_Article_Blog_LeftCurlyBracketKeyword_0_or_LeftCurlyBracketKeyword_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getArticleAccess().getLeftCurlyBracketKeyword_0()), new TokenAlias(false, false, grammarAccess.getBlogAccess().getLeftCurlyBracketKeyword_0()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Article_Blog_LeftCurlyBracketKeyword_0_or_LeftCurlyBracketKeyword_0.equals(syntax))
				emit_Article_Blog_LeftCurlyBracketKeyword_0_or_LeftCurlyBracketKeyword_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '{' | '{'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'title=' name=ALPHANUMERICDASH
	 */
	protected void emit_Article_Blog_LeftCurlyBracketKeyword_0_or_LeftCurlyBracketKeyword_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
